# Generated by Django 4.2 on 2023-10-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeItem',
            new_name='RecipeItems',
        ),
    ]
