# Generated by Django 4.2 on 2023-10-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0002_rename_recipeitem_recipeitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsrest.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsrest.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeItems',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(through='hmsrest.RecipeItem', to='hmsrest.item'),
        ),
    ]
