# Generated by Django 4.2 on 2023-10-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0004_remove_dish_items_remove_dish_recipes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('theoretical_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('error_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsrest.dish')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsrest.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='DishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsrest.dish')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsrest.item')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='items',
            field=models.ManyToManyField(through='hmsrest.DishItem', to='hmsrest.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipes',
            field=models.ManyToManyField(through='hmsrest.DishRecipe', to='hmsrest.recipe'),
        ),
    ]
