# Generated by Django 4.2 on 2023-10-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0006_dailymenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyMenu',
        ),
    ]
