# Generated by Django 4.2 on 2023-10-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0008_dailymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='name',
        ),
    ]
